// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppsProsjekt1.Models;

#nullable disable

namespace WebAppsProsjekt1.Migrations
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("WebAppsProsjekt1.Models.Cardset", b =>
                {
                    b.Property<int>("CardSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardSetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("CardSetId");

                    b.ToTable("Cardsets");
                });

            modelBuilder.Entity("WebAppsProsjekt1.Models.FlashCard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CardsetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("FlashcardId");

                    b.HasIndex("CardsetId");

                    b.ToTable("FlashCards");
                });

            modelBuilder.Entity("WebAppsProsjekt1.Models.FlashCard", b =>
                {
                    b.HasOne("WebAppsProsjekt1.Models.Cardset", "Cardset")
                        .WithMany("CardList")
                        .HasForeignKey("CardsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardset");
                });

            modelBuilder.Entity("WebAppsProsjekt1.Models.Cardset", b =>
                {
                    b.Navigation("CardList");
                });
#pragma warning restore 612, 618
        }
    }
}
